//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientTeaShopWpf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chek
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public string CVC { get; set; }
        public Nullable<int> BankId { get; set; }
        public Nullable<System.DateTime> Age { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<decimal> Balance { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual User User { get; set; }
    }
}
